image: google/cloud-sdk:latest

variables:
  GCP_REGION: "us-central1"
  APP_NAME: "customer-segmentation-app"
  REPO_NAME: "customer-segmentation-repo"
  IMAGE_NAME: "us-central1-docker.pkg.dev/customer-segmentation-465514/customer-segmentation-repo"

stages:
  - build
  - deploy

build:
  stage: build
  only:
    - main
  script:
    - echo "Authenticating with Google Cloud..."
    - gcloud auth activate-service-account --key-file $GCP_SERVICE_ACCOUNT_KEY
    - echo "Configuring Docker to use gcloud as a credential helper..."
    - gcloud auth configure-docker $GCP_REGION-docker.pkg.dev
    - echo "Building the Docker image with Google Cloud Build..."
    # - gcloud builds submit --no-source --tag "$IMAGE_NAME:$CI_COMMIT_SHORT_SHA"
    - gcloud builds submit . --project="customer-segmentation-465514" --gcs-source-staging-dir="gs://customer-segmentation-cloudbuild/source" --tag "${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}" --quiet
    - echo "Build complete."

deploy:
  stage: deploy
  only:
    - main
  script:
    - echo "Authenticating with Google Cloud..."
    - gcloud auth activate-service-account --key-file $GCP_SERVICE_ACCOUNT_KEY
    - echo "Deploying to Google Cloud Run..."
    - gcloud run deploy $APP_NAME \
        --image "$IMAGE_NAME:$CI_COMMIT_SHORT_SHA" \
        --platform "managed" \
        --region "$GCP_REGION" \
        --allow-unauthenticated # Use --no-allow-unauthenticated for private services
    - echo "Deployment complete."
