# image: google/cloud-sdk:latest

# variables:
#   GCP_REGION: "us-central1"
#   APP_NAME: "customer-segmentation-app"
#   REPO_NAME: "customer-segmentation-repo"
#   IMAGE_NAME: "us-central1-docker.pkg.dev/customer-segmentation-465514/customer-segmentation-repo"

# stages:
#   - build
#   - deploy

# build:
#   stage: build
#   only:
#     - main
#   script:
#     - echo "Authenticating with Google Cloud..."
#     - gcloud auth activate-service-account --key-file $GCP_SERVICE_ACCOUNT_KEY
#     - echo "Configuring Docker to use gcloud as a credential helper..."
#     - gcloud auth configure-docker $GCP_REGION-docker.pkg.dev
#     - echo "Building the Docker image with Google Cloud Build..."
#     - gcloud builds submit . --tag "$IMAGE_NAME:$CI_COMMIT_SHORT_SHA"
#     - echo "Build complete."

# deploy:
#   stage: deploy
#   only:
#     - main
#   script:
#     - echo "Authenticating with Google Cloud..."
#     - gcloud auth activate-service-account --key-file $GCP_SERVICE_ACCOUNT_KEY
#     - echo "Deploying to Google Cloud Run..."
#     - gcloud run deploy $APP_NAME \
#         --image "$IMAGE_NAME:$CI_COMMIT_SHORT_SHA" \
#         --platform "managed" \
#         --region "$GCP_REGION" \
#         --allow-unauthenticated # Use --no-allow-unauthenticated for private services
#     - echo "Deployment complete."


variables:
  GCP_REGION: "us-central1"
  APP_NAME: "customer-segmentation-app"
  REPO_NAME: "customer-segmentation-repo"
  IMAGE_NAME: "$GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/$REPO_NAME/$APP_NAME"

stages:
  - build
  - deploy

build:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  only:
    - main
  script:
    - apk add --no-cache google-cloud-cli
    
    - echo "Authenticating with Google Cloud..."
    - echo $GCP_SERVICE_ACCOUNT_KEY > /tmp/gcp_key.json
    - gcloud auth activate-service-account --key-file=/tmp/gcp_key.json
    
    - echo "Configuring Docker..."
    - gcloud auth configure-docker $GCP_REGION-docker.pkg.dev
    
    - echo "Building the Docker image..."
    - docker build -t "$IMAGE_NAME:$CI_COMMIT_SHORT_SHA" .
    
    - echo "Pushing image to Artifact Registry..."
    - docker push "$IMAGE_NAME:$CI_COMMIT_SHORT_SHA"
    - echo "Build complete."

deploy:
  stage: deploy
  image: google/cloud-sdk:latest
  only:
    - main
  script:
    - echo "Authenticating with Google Cloud..."
    - gcloud auth activate-service-account --key-file $GCP_SERVICE_ACCOUNT_KEY
    - echo "Deploying to Google Cloud Run..."
    - gcloud run deploy $APP_NAME \
        --image "$IMAGE_NAME:$CI_COMMIT_SHORT_SHA" \
        --platform "managed" \
        --region "$GCP_REGION" \
        --allow-unauthenticated
    - echo "Deployment complete."