[server]
enableStaticServing=true

[[theme.fontFaces]]
family="DMSans"
url="app/static/DMSans-VariableFont_opsz,wght.ttf"
style="normal"

[[theme.fontFaces]]
family="DMSans"
url="app/static/DMSans-Italic-VariableFont_opsz,wght.ttf"
style="italic"

[theme]
font="DMSans"
primaryColor="goldenrod"
borderColor="gold"
showWidgetBorder=true

[theme.sidebar]
showWidgetBorder=true

[server]
maxUploadSize = 500